Update UltraPermissions_Italian.lang
TechsCode/PluginTranslations pull request #57
Opened 2021-04-10 23:11 UTC by ItsWagPvP

2021-04-15 21:38 UTC, Greazi-Times requested changes
Lines that are not translated need to keep the # in front of the lines

2021-05-13 20:30 UTC, ItsWagPvP commented
Sorry for the long-time wait

2021-05-15 12:05 UTC, Greazi-Times approved these changes, later dismissed

2021-05-15 12:07 UTC, Greazi-Times approved these changes

2021-05-15 12:07 UTC, merged